parameters:
#    blog_general.example.class: Blog\GeneralBundle\Example

services:
#    blog_general.example:
#        class: %blog_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
